### ISSUE TITLE
Add an option to update tracking when marked as read

### ISSUE THREAD

**Issue by kana-shii** [komikku-app/komikku#1]
### Describe your suggested feature

The app only syncs when I get to the last page of the chapter. That's a problem because when I read online, I can't simply mark the chapter as read to have it update the tracker.
This is an option from TachiyomiJ2K.

### Other details

![image](https://github.com/komikku-app/komikku/assets/79055104/66b7b05f-ca3f-4c5e-a4ac-1cc0b58aa4ca)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by kana-shii** [comment]
Sorry. Forgot to explain more about what it does. @cuong-tran 
It would basically do the same thing as the "Update tracking after reading", but instead of actually having to read the complete chapter until the last page, you can mark it as read for the tracker to update.
I'm unfortunately not knowledgeable enough to explain how to do it, but I really hope that this turns into a feature. It's something that would help a lot.

**Comment by cuong-tran** [comment]
No  worry, I understand the request

**Comment by aoba-seragakii** [comment]
Hello. Any idea on when this will be released?
