### ISSUE TITLE
Sortable Feed

### ISSUE THREAD

**Issue by JoeloJoestar** [komikku-app/komikku#130]
### Describe your suggested feature

I want to have many feed items from multiple sources in the Feed section. Those rows are ordered only by last feed item added. It would be cool to have options to sort:
- Alphabetically
- By source, then alphabetically
- Custom and drag-and-drop-able

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
completed with #220 & #356
