### ISSUE TITLE
Drag and drop categories

### ISSUE THREAD

**Issue by JoeloJoestar** [komikku-app/komikku#131]
### Describe your suggested feature

I would like to order categories in their settings by drag and drop, instead of hating my life by crazy tapping.
The download queue is sortable like that already, so why not for categories too?

### Other details

I remember such a request to TachiyomiSY and the response was something about updating compose first. Well, at least 1 year passed by.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
Done with PR #508
