### ISSUE TITLE
Read filtered chapters from the reader

### ISSUE THREAD

**Issue by fellinir** [komikku-app/komikku#132]
### Describe your suggested feature

Especially for those manga having many chapters, I apply the filter **Unread** and sort them up by **Ascending Chap #** so that when I re enter the entry I always see the next unread chapter first.
Problem is, if I for example read this new chapter and I wanna peek at previous ones from the reader, by swiping back from the 1st page of the new chapter, then it tells me there are not chapters available, since those are filtered out, and so I must go back, adjust the filter, scroll down to find that chapter, read it, then go back again and reapply the filter.

Maybe we can have a query asking us if we are sure to view the filtered chapter from the reader?
Anything that could improve QoL.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
Have you tried turn off the option "Skip filtered chapters" in Reader settings?

**Comment by fellinir** [comment]
@cuong-tran turning that off now solved it. Thank you.
