### ISSUE TITLE
Laggy after displaying many entries

### ISSUE THREAD

**Issue by fellinir** [komikku-app/komikku#159]
### Steps to reproduce

1. Have dynamic theme active
1. Open and close several entries in a row

### Expected behavior

There is no lag or slow down

### Actual behavior

Scrolling, especially horizontally though categories, is way slower and laggy.
The system in general actually, like too much RAM is filled up and not cleaned on time.

### Komikku version

r9115

### Android version

Android 12

### Device

Lenovo tab m10 plus 3rd Gen (Qualcomm)

### Other details

I assume it has something to do with the dynamic theme because such issue isn't present in the latest SY preview.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
Yep i found the same problem here

**Comment by cuong-tran** [comment]
Does it happen with r9078 or v1.11.1?

**Comment by fellinir** [comment]
@cuong-tran yes, same issue with r9078

**Comment by cuong-tran** [comment]
could you help share a video record?

**Comment by fellinir** [comment]
> could you help share a video record?


https://github.com/komikku-app/komikku/assets/92597054/472578c9-f878-4e24-8f17-cc470718a7c1

Did it on my phone instead of my tablet bcs same thing happens here. See how hard it gets to change category, especially by swiping.

**Comment by cuong-tran** [comment]
I can see it. Could you try same thing but with "Browse->Related titles" or "Appearance->Expand Related titles" turned off?

**Comment by fellinir** [comment]
@cuong-tran those two settings were already off.

**Comment by fellinir** [comment]
Other things I have just noticed:

- No need to open entries to make it all slow, it's enough to scroll vertically and through categories, displaying many entries.
- It doesn't slow the OS down, but the whole up. All is laggy: Library, Browse, Settings.
- Reading pages flows fluently though, and after spending enough time reading, going back to library you see it "fixed" and the UI is smooth. The problem though still persists after moving around.

**Comment by cuong-tran** [comment]
Thanks. I will run profiler to see why
