### ISSUE TITLE
Range selection of chapters!

### ISSUE THREAD

**Issue by yuvsama001** [komikku-app/komikku#177]
### Describe your suggested feature

Like in J2k, when you long press on chapter it will select the and asks for last/intended chapter to select then it will ask for choose an operation.
And if you long press on download icon it will ask same thing from where to start and end the selection for downloading chapters.
![Screenshot_2024-07-17-08-04-29-20_21015a41200050f19d2d2db913bd7dc1](https://github.com/user-attachments/assets/aabb11b8-7eeb-4447-a391-1e3e214e5036)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by fellinir** [comment]
You can already select a range of chapters by long pressing the first and then the last one you want.

**Comment by yuvsama001** [comment]
> You can already select a range of chapters by long pressing the first and then the last one you want.

Thanks I didn't know that!
