### ISSUE TITLE
Can't Copy the manga through Migrate.

### ISSUE THREAD

**Issue by yuvsama001** [komikku-app/komikku#188]
### Steps to reproduce

1. Select a manga from Library.
2. Click on three dots, then Migrate.
3. Select the Source and necessary options. (I have untick the delete downloaded option but still it deleted all Chapters.)
4. Then select the manga from the Source.
5. Try copying it from three dots besides the manga. (Didn't work)
6. Tried the Copy Icon. Instead of copying it Migrated the Manga.

### Expected behavior

Code problem maybe?

### Actual behavior

The process works fine in Yokai (Tachij2k forked version) but in komikku it didn't work.
So, please try to fix it and the delete the chapters option also.

### Crash logs

Here's a Screen recording.

### Komikku version

Beta r9149

### Android version

Android 11

### Device

Realme 7i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
You should describe the "Actual behavior" more clearly. Is it:
1. Untick "Delete downloaded" but it still deletes downloaded chapters
2. Use the Copy icon but it migrates instead of copy.

Anything else?

**Comment by yuvsama001** [comment]
> You should describe the "Actual behavior" more clearly. Is it:
> 
> 1. Untick "Delete downloaded" but it still deletes downloaded chapters
> 2. Use the Copy icon but it migrates instead of copy.
> 
> Anything else?

Nope, that's it.
