### ISSUE TITLE
Please make sure that the settings options are properly applied to the app.

### ISSUE THREAD

**Issue by FrankieD777** [komikku-app/komikku#239]
### Steps to reproduce

1. I open the application.
2. I navigate to the settings section.
3. I make some changes.
4. 
![Screenshot_20240807-170016](https://github.com/user-attachments/assets/edc335aa-319f-4b9e-a0c1-29ce5240bf70)

### Expected behavior

The changes are applied.

### Actual behavior

It continues to be the same experience. Even if you adjust the settings, the application doesn't show any noticeable difference.
![Screenshot_20240807-170027](https://github.com/user-attachments/assets/10e547d1-cb14-47b7-b913-6f9e63ef7f07)

### Komikku version

Komikku  1.11.1-9197

### Android version

Android 14 basado en Hios

### Device

TECNO SPARK 20 Pro

### Other details

 ¿Podrían echarle un vistazo y arreglar esto lo más pronto posible, por favor? ¡Mil gracias! 😊

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.1](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
You got to tell me exactly what setting changes doesn't work.

Also, from your screenshot, all the settings appear on that picture will have their effects somewhere else but not on the extension list, as shown in 2nd screenshot. You might misunderstand what those settings do.

One more thing, why do the extensions in your list appear "No Official"?

**Comment by JoeloJoestar** [comment]
> One more thing, why do the extensions in your list appear "No Official"?

It's "NO OFICIAL". It should be the Spanish l18n for UNOFFICIAL, so extensions installed outside of Komikku.

**Comment by FrankieD777** [comment]
That's exactly what I'm talking about, dude. Isn't there supposed to be an option to accept extensions from outside? Also, the integrated hentai option isn't deactivated.

**Comment by FrankieD777** [comment]
Translate to English:
---
> You have to tell me exactly which configuration changes are not working.
> 
> Also, according to the screenshot, all the settings that appear in that image will take effect elsewhere, but not in the extensions list, as shown in the second screenshot. It’s possible that you don't understand what those settings do.
> 
> One more thing, why do the extensions in your list appear as "Unofficial"?

And by the way, what doesn’t get deactivated or always stays active is each of the options in the advanced section. Show result only

**Comment by FrankieD777** [comment]
Well, I hope my comment doesn't get ignored. I used to love this app, it was one of my top favorites when I was using forks of Mihon and Tachiyomi! But I have noticed some recent changes regarding interface glitches that I don't like at all and I would like to talk about that. Thanks for understanding and for continuing to improve this application which truly fascinates me!

**Comment by FrankieD777** [comment]
Sure, here is the translation:

> > That's exactly what I'm talking about, dude. Isn't there supposed to be an option to accept extensions from outside? Also, the integrated hentai option isn't deactivated. Even though I turn it off.
> 
> You can check out that the hentai option is deactivated through the settings. If it was truly activated, there would be an E-Hentai part right after "Security and Privacy". To deactivate +18 extensions, just click the +18 icon. It has nothing to do with the integrated hentai options.
> 
> If you add the repo where you installed them from, I think that you can remove that message. There will eventually be an option to remove the komikku repo, so you have three options:
> 
> 1. Install every extension again through komikku's repo
> 2. Add the repo you're using to the "extension repo" on the komikku app (although it will make every extension duplicate)
> 3. wait for the option to remove the komikku repo
> 
> also, it would be easier to talk about some stuff through the discord server instead, so make sure to enter it

Sorry if this might sound rude or could result in a ban from your servers. At first, perhaps I didn't explain myself well, but what I want is for the app not to show that "unofficial" label and for the hentai extension upgrade not to be implemented, as reinstalling everything is arduous work. If something happens to the app and I have to switch temporarily until it's fixed, it would be a big hassle. In short, I want external elements to be allowed in the app without additional notifications and to generate trust like almost all Tachiyomi and Aniyomi forks. Believe me, this would be a great relief for most users who move to this fork, kumikku,

**Comment by cuong-tran** [comment]
To hide 18+ extensions, go to Settings -> Browse and scroll all the way down bottom.
For the "no official" tag, I have no plan to ditch it yet, at least until the new repo feature released.
Go to Discord to ask for support, you could start with asking "what this does?" instead of jumping to conclusions "this not working".
Anyway, no one will be banned just by rude talking, unless they are trying to insult others for no good reason.

I'm closing this since it's not actually a bug.
