### ISSUE TITLE
Good afternoon, I'm posting this here because the font issue session won't open.

### ISSUE THREAD

**Issue by FrankieD777** [komikku-app/komikku#249]
### Steps to reproduce

1. Iniciar la aplicación.

2. Proceder a ejecutar la acción requerida.

3. Seleccionar una extensión.

4. Escoger un manga y leer un capítulo 

### Expected behavior

¡Leer tranquilamente sin problema! 🌟📚

### Actual behavior

Los capítulos de varias de sus muchas extensiones se duplican en cada manga
![Screenshot_20240811-122713](https://github.com/user-attachments/assets/71604858-b4dd-465d-9fab-b786a87bc8fb)

### Crash logs

![Screenshot_20240811-122639](https://github.com/user-attachments/assets/b20b153e-8c16-4c9f-85b2-812f4ea441b3)
![Screenshot_20240811-122554](https://github.com/user-attachments/assets/fb2dd7b9-c775-4e5e-ac18-51487908f57b)
![Screenshot_20240811-122524](https://github.com/user-attachments/assets/bcc34cde-ef3b-416b-8e13-fa001f5830e3)
![Screenshot_20240811-122504](https://github.com/user-attachments/assets/13256664-1925-4a2c-ac17-dff7dd741c2b)

### Komikku version

Komikku  1.11.2

### Android version

Android 13(Hios Basado en AndroidV12.6.0)

### Device

TECNO SPARK 10 Pro

### Other details

Estimados,

Espero se encuentren bien. Me comunico nuevamente para informar sobre un inconveniente que he detectado; los capítulos están duplicándose. Considero que esto podría deberse a algunas de las extensiones personalizadas que estoy utilizando. Para resolverlo, eliminé todas las extensiones actuales y reinstalé las que se encuentran en su repositorio oficial.

Sin embargo, si vuelvo a instalar las extensiones anteriores, me enfrento al problema de que no figuran como oficiales y es necesario actualizarlas manualmente.

Agradecería su asistencia para solucionar este inconveniente.
![Screenshot_20240811-122743](https://github.com/user-attachments/assets/2f930b7b-99ae-416a-8b0e-8de79d28d7d2)

Y ahi lo que mencione de el catalogo de reportar problemas de extensión
![Screenshot_20240811-122828](https://github.com/user-attachments/assets/d5c0bdc0-91eb-46fd-9558-6a33eca6f700)
Y esto la prueba de que alguna extensiones no duplican el contenido

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
Try [this](https://github.com/orgs/komikku-app/discussions/247#discussioncomment-10306449)
Even the issue which chapters appear wrong order, it's same.

**Comment by FrankieD777** [comment]
Try [this](https://github.com/orgs/komikku-app/discussions/247#discussioncomment-10306449). Even with the issue of chapters appearing in the wrong order, it remains the same.

I'm sorry to say that didn't solve the problem. Please update the app extensions to a suitable level for proper use.

**Comment by FrankieD777** [comment]
If I may, I would suggest implementing an option called "Force Library Reindexing" to ensure that all manga chapters load correctly.

**Comment by cuong-tran** [comment]
suggestion on #250
