### ISSUE TITLE
Library reindexing.

### ISSUE THREAD

**Issue by FrankieD777** [komikku-app/komikku#250]
### Describe your suggested feature

Good afternoon,

I hope you are well. I am pleased to share a proposal that has developed from my experience with an open-source music player called Namida. The feature I am proposing has similarities with the download index rebuild function but implemented in an online environment. This functionality would allow reloading all episodes of the mangas in the library and automatically updating the covers.

Best regards.

### Other details

Hello everyone!

We want to ask for your help to resolve the issues with duplicate chapters that some users have been experiencing lately. We greatly appreciate you taking a moment to read this and hope you can help us resolve it. Many thanks in advance!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by xdeiimoss** [comment]
I also have this same problem. I'm unable to use previous backups because I already don't have them and there are to many entries with this issue to remove them and re-add them. 
![image](https://github.com/user-attachments/assets/6b84abab-fb39-4170-ad77-9e4a683db9ed)

**Comment by cuong-tran** [comment]
Duplicated chapters issue is solved with PR #565
