### ISSUE TITLE
App crashes upon migrating changing tracker and removing from kitsu

### ISSUE THREAD

**Issue by HikaruIchijyo** [komikku-app/komikku#257]
App crashes as soon as i add a manga which was previously added to kitsu to anilist & remove from kitsu app crashes logs attached

![tachiyomi_crash_logs.txt](https://github.com/user-attachments/files/16637625/tachiyomi_crash_logs.txt)

**Comment by cuong-tran** [comment]
Does this still happen on latest preview build (r9234) since Kitsu update their domain so it might be the cause.

**Comment by HikaruIchijyo** [comment]
> Does this still happen on latest preview build (r9234) since Kitsu update their domain so it might be the cause.

i am on stable.
i will chk preview?

**Comment by HikaruIchijyo** [comment]
this got fixed in preview
