### ISSUE TITLE
Coloring information similar to this 

### ISSUE THREAD

**Issue by OtakuArab** [komikku-app/komikku#292]
### Describe your suggested feature

See the coloring of this app
![Screenshot_٢٠٢٤٠٨٢٥-٠٩٠٧٠٧_NovelWorld](https://github.com/user-attachments/assets/76cfde93-52ca-4908-973a-539747a4695b)
Business Links
https://github.com/jakepurple13/OtakuWorld/releases/tag/v31.0.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
What is exactly "like this" do you mean? please describe it.
