### ISSUE TITLE
Do not depend on tachiyomiSy

### ISSUE THREAD

**Issue by AbdelrahmanElnezamy121** [komikku-app/komikku#3]
### Describe your suggested feature

If you can make a fork of original Mihon it will be better than tachiyomiSy 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
TachiyomiSY regularly takes updates from Mihon too. Is there any particular issue you think TachiyomiSY is worse than Mihon, I would love to know.

**Comment by cuong-tran** [comment]
> > TachiyomiSY regularly takes updates from Mihon too. Is there any particular issue you think TachiyomiSY is worse than Mihon, I would love to know.
> 
> To be fare, tho I love tachiSY(and I think that froking from it is better), since it's using sql databases and reading from them then searching is much slower(or something like that can't remember correctly)

There is another opened issue mention that. I will try to see if I can merge Mihon's database management. Thanks.

**Comment by cuong-tran** [comment]
Both Mihon & TachiyomiSY using same SQLite mechanism so nothing is different.
