### ISSUE TITLE
Hide categories

### ISSUE THREAD

**Issue by aoba-seragakii** [komikku-app/komikku#320]
### Describe your suggested feature

This is a feature from Aniyomi. It lets users hide categories from their library.
It's a really good feature.
For reference: https://github.com/aniyomiorg/aniyomi/pull/1125

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Genzales6** [comment]
i like the idea I hope you implement it
