### ISSUE TITLE
Add error badge or/and error filter

### ISSUE THREAD

**Issue by xdeiimoss** [komikku-app/komikku#323]
### Describe your suggested feature

An error badge/filter for when an update fails

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by isabella-almeidaa** [comment]
https://github.com/mihonapp/mihon/pull/757

**Comment by cuong-tran** [comment]
I have same opinion with [Ansylich](https://github.com/mihonapp/mihon/pull/757#issuecomment-2093501514) on this.

**Comment by isabella-almeidaa** [comment]
> I have same opinion with [Ansylich](https://github.com/mihonapp/mihon/pull/757#issuecomment-2093501514) on this.

Okay, no problem. Would it be possible to know which entries have errors even if the automatic update didn't ended?

**Comment by cuong-tran** [comment]
> > I have same opinion with [Ansylich](https://github.com/mihonapp/mihon/pull/757#issuecomment-2093501514) on this.
> 
> Okay, no problem. Would it be possible to know which entries have errors even if the automatic update didn't ended?

It should be possible to know the error status right after each entry update, no need to wait till the end
