### ISSUE TITLE
Include extension settings in backups

### ISSUE THREAD

**Issue by isabella-almeidaa** [komikku-app/komikku#353]
### Describe your suggested feature

Please include extension settings in backups.
Some extensions have multiple languages and sometimes it takes long to configure everything, so it would be incredible to not have to configure everything again if it was included in the backups.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
It should be already included, unless you are using the stable build then maybe it's still in preview build, waiting to get to stable.

**Comment by isabella-almeidaa** [comment]
Okay thanks
