### ISSUE TITLE
Extensions-source Classification

### ISSUE THREAD

**Issue by RejectVanity** [komikku-app/komikku#378]
### Describe your suggested feature

Extensions-source categories, and allow selecting specific categories of Extensions-source during search, instead of only being able to use all Extensions-source.

This function can refer to [Legado](https://github.com/gedoor/legado).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
it's being implemented right now
