### ISSUE TITLE
Option to Auto-Download New Chapters for Series Only If No Unread Chapters

### ISSUE THREAD

**Issue by jeyemrs** [komikku-app/komikku#379]
### Describe your suggested feature

Basically an option that automatically downloads new chapters from a series ONLY if you don't have any unread chapters. It could be a suboption for "Download new chapters" that you can choose whether you turn on or off.

### Other details

The only thing that I skip on the Smart Update is for entries with completed status. So if I do a global update, I'll get new chapters even if I have unread chapters. The reason for this is because I still want to know that the said series have new chapters, so I'll know that I have enough to binge-read haha. With that said, because of this I can't turn on the auto-download new chapters because it will download them all. I want an option to just download new chapters from entries that I have no unread chapters—series that I don't want to gather chapters first before I read because I really want to stay updated on it. 

Before, I actually skip entries with unread chapters on Smart Update, so I have no problem with auto-download. But, that makes it so that I won't know whether the entries I'm waiting to gather more chapters to binge-read have new chapters. In the end, sometimes I even forgot the said series lol.

I hope you consider it, thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
You can do this:
- Create a category named "Skip-download"
- Go to Settings/Downloads/Auto-download then add that category to Exclude.
If you are using preview version then you can hide that category from Library if you don't want to see it.

**Comment by cuong-tran** [comment]
Yes, manual but better control rather than an option for entire library.

**Comment by kana-shii** [comment]
> > Yes, manual but better control rather than an option for entire library.
> 
> Hello again. So I tried it and it works, but the option you told me to hide categories doesn't work somehow. You need to click the "eye" button right? It's not hidden for some reason.

To actually hide them, go to your library, press the 3 horizontal lines, go to display and click on "Hide hidden categories"

**Comment by cuong-tran** [comment]
Maybe I should enable the option by default.

**Comment by JoeloJoestar** [comment]
@cuong-tran then by default the filter in the library will be yellow and so active?
How about switching the logic: the filter will be inactive by default but it's the opposite logic "show hidden categories". And so we also avoid the confusing double negation.

**Comment by cuong-tran** [comment]
Cool

**Comment by cuong-tran** [comment]
> @cuong-tran then by default the filter in the library will be yellow and so active? How about switching the logic: the filter will be inactive by default but it's the opposite logic "show hidden categories". And so we also avoid the confusing double negation.

I did it just following your suggestion. Thank you.
