### ISSUE TITLE
option to disable Source for source

### ISSUE THREAD

**Issue by julptk** [komikku-app/komikku#38]
### Describe your suggested feature

request for disable option Search for source on browse

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
Do you mean excluding some sources from global search?
