### ISSUE TITLE
Option to add tracking to multiple entries at once

### ISSUE THREAD

**Issue by DemiM0rt** [komikku-app/komikku#391]
### Describe your suggested feature

Currently, you can only track entries one by one, this is very time consuming.

It also discourage users from using/migrate tracking service when they have large libraries.

This feature would let you track multiple entries at once and reduce the manual work needed to start using tracking services.

### Other details

Here are some suggestions on how I would like feature to be.

- When selecting entries in the library, add a new option for tracking in the bottom/overflow menu.
- add a pop up asking which tracking service to use.
- add a screen like migration with similar feature (manual search, cancel tracking, track now and track all).
 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
Close this as it's not really a good thing:
- It's unlikely to find the entry in tracker correctly automatically.
- There are multiple trackers, that make finding it correctly more difficult.

Also see: https://github.com/mihonapp/mihon/issues/1208
