### ISSUE TITLE
Mark as read won't Delete downloaded chapter

### ISSUE THREAD

**Issue by HikaruIchijyo** [komikku-app/komikku#394]
### Steps to reproduce

if u have read all the chapters & somehow u have some downloaded chapters even if u select mark below chapters as read it won't delete unless u manually click on downloaded icon & click on delete

### Expected behavior

it should remove downloaded chapter even though if it is already read

### Actual behavior

it doesn't delete the chapter

### Komikku version

1.11.2

### Android version

14

### Device

poco f6

### Other details

either add an option to delete all mark as read chapters in settings or maybe make the behaviour so that if select option mark below as read should delete the downloaded chapter even though those chapters are already marked read

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
I don't experience this issue. Have you checked if the category is in the excluded list in Settings?

**Comment by HikaruIchijyo** [comment]
> I don't experience this issue. Have you checked if the category is in the excluded list in Settings?

u didn't get my point i will try to record a video

**Comment by HikaruIchijyo** [comment]
> I don't experience this issue. Have you checked if the category is in the excluded list in Settings?

chk this

https://github.com/user-attachments/assets/fde80ff7-04f2-4eea-923d-6f08e36cca95

**Comment by cuong-tran** [comment]
> > I don't experience this issue. Have you checked if the category is in the excluded list in Settings?
> 
> nope it is selected to none.
> 
> do this. if u have read a whole manga download any read chapter then click on mark below as read it wont delete that chapter from downloads lemme rechk

do you mean, if you select 1 chapter then hit the **"Mark previous as read"** on the bottom bar, the entry won't got delete?

It only works when a chapter is **switching** from un-read/reading to read, it won't work if the chapter is already read.
The option _Mark previous as read_ or when select all chapters & _Mark as read_ works in a way it would find the un-read/reading chapters first, then mark them as read, following with delete their download. It won't try to do everything on every chapters.

Work around is select all chapters, mark them as unread first then mark them as read again

**Comment by HikaruIchijyo** [comment]
> > > I don't experience this issue. Have you checked if the category is in the excluded list in Settings?
> > 
> > nope it is selected to none.
> > 
> > do this. if u have read a whole manga download any read chapter then click on mark below as read it wont delete that chapter from downloads lemme rechk
> 
> do you mean, if you select 1 chapter then hit the **"Mark previous as read"** on the bottom bar, the entry won't got delete?
> 
> It only works when a chapter is **switching** from un-read/reading to read, it won't work if the chapter is already read.
> The option _Mark previous as read_ or when select all chapters & _Mark as read_ works in a way it would find the un-read/reading chapters first, then mark them as read, following with delete their download. It won't try to do everything on every chapters.
> 
> Work around is select all chapters, mark them as unread first then mark them as read again


yep yeah that's how i am using by workaround like that

**Comment by cuong-tran** [comment]
There is also the button to delete selected chapters. That should be how it is. I'm closing this. Thanks.
