### ISSUE TITLE
Mark as read to track not working

### ISSUE THREAD

**Issue by aoba-seragakii** [komikku-app/komikku#396]
### Steps to reproduce

mark any chapter as read
check the tracker
tracker should update automatically

### Expected behavior

tracker updates automatically

### Actual behavior

it doesn't change anything

### Komikku version

r9404

### Android version

Android 12

### Device

Google Pixel 6 Pro

### Other details

was working correctly before

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
this is due to a commit from Mihon requires user now to manually hit OK to update tracker. It was reverted.
