### ISSUE TITLE
manga don't show up in library

### ISSUE THREAD

**Issue by 00pandora00** [komikku-app/komikku#397]
### Steps to reproduce

1. trying to add manga from website (manga fire en, manganato en)
2.  program says that the manga is added
3. manga don't show up
(Note: the manga i'm trying to add is "Souzou Renkinjutsushi wa Jiyuu wo Ouka suru: Kokyou wo Tsuihou saretara, Maou no Ohizamoto de Chouzetsu Kouka no Magic Item Tsukuri-houdai ni Narimashita ")

### Expected behavior

manga  should show in library

### Actual behavior

manga don't show up in the librerary

### Komikku version

1.59.0 (flatpak)

### Android version

Linux

### Device

pc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by JoeloJoestar** [comment]
Have you checked if it's in the category "Default"?

**Comment by JoeloJoestar** [comment]
Also, if you see the Manga hearted ♥ meaning it's saved in the library, press and hold that cutie ♥ and it will show you in which category have fallen in love of.

**Comment by 00pandora00** [comment]
> Have you checked if it's in the category "Default"?

don't worry the problem was fixed. 
(I accidently "set on" some of the options in the search bar xD)
