### ISSUE TITLE
Resume update if it crashes in the middle 

### ISSUE THREAD

**Issue by aoba-seragakii** [komikku-app/komikku#398]
### Describe your suggested feature

Sometimes, the app ends up crashing in the middle of an update, and then it starts all over again once the user opens the app again.
Instead of doing that, I think it would be better if the update continued right before the crash, so it doesn't strain the sources by updating the same entries all over again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by aoba-seragakii** [comment]
Just an idea:
Maybe this could be included on the error screen thing
Maybe the entries that didn't update because of crashes could be added to the library error as an error itself. But the app would probably need to know what exactly it was supposee to update + list everything that is already done so it remember where it should start from

**Comment by cuong-tran** [comment]
I think AntsyLich answered on https://github.com/mihonapp/mihon/issues/1281.
- Turn on "Predict next release time" so then it will check for update on entries with the predicted date. Entries which was successful checked will have its next update day pushed to the future so the next time you run update, they won't be included. Only those did not finished checking for update in the previous crashed checking will be checked next time.
- If you update twice a day with that option off, it's not encouraged.
- Put the failed entries aside, if you want it to be able to know the last update is crashed and will restart itself, that is also not good. The update was crashed might come from various reasons. Trying to restart itself all the time could lead to unwanted effect like draining battery, massive network data consumed... Especially if you run update twice a day then just wait till next run.

So, I'm closing this.

**Comment by aoba-seragakii** [comment]
The update reruns by itself, also I am using predict next release time

**Comment by cuong-tran** [comment]
then you should good to go. That option is exactly for the case to resume update only entries needed to update, not one already updated.

**Comment by aoba-seragakii** [comment]
Ok
