### ISSUE TITLE
Consider the Smart Updates settings on upcoming screen

### ISSUE THREAD

**Issue by aoba-seragakii** [komikku-app/komikku#400]
### Describe your suggested feature

I think that the manga shown on the upcoming screen should change depending on the Smart Updates settings

Example:
X manga is still ongoing but I still haven't started reading it yet, and I've activated "Skip unstarted entries".
Y manga is also ongoing but I've read it until the latest chapter
Z manga is ongoing, I've read the first chapter but I didn't continue reading it so if I activate "Skip entries with unread chapters" it shouldn't appear on the upcoming screen. But I didn't activated this option so it should appear
X manga shouldn't appear on the upcoming screen because I've activated "Skip unstarted entries"
Y manga should appear because I've read until the latest chapter
Z manga should also appear because I didn't activated "Skip entries with unread chapters", but if I did activate it it shouldn't show up
Same thing for category exclusion

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
if PR #413 is implemented, then this can go into that, it should be the "Checking for update" screen instead of "Upcoming" screen
