### ISSUE TITLE
Custom theme: wrong background and accent color of download queue

### ISSUE THREAD

**Issue by JoeloJoestar** [komikku-app/komikku#401]
### Steps to reproduce

1. Use the library theme **Custom theme**
2. Pick any color
3. Start downloading some chapter
4. Go to **Download**

### Expected behavior

The background and foreground colors of the chapters in queue follow the custom theme

### Actual behavior

The background and foreground colors of the chapters in queue are always the same:
- Grey background which stands out. With other themes I don't see such bold background
- Blue progress bar

![Screenshot_20241001-053711_Komikku](https://github.com/user-attachments/assets/ae0c280b-8c0e-4720-a283-494839a09526)

### Komikku version

r9404

### Android version

12, 13

### Device

Lenovo Tab M10, OnePlus 5T

### Other details

No matter the color or the choice in the palette personalizer you pick, those colors stay the same
![Screenshot_20241001-053659_Komikku](https://github.com/user-attachments/assets/f561b89f-ca13-4837-a4f5-ddd59be9c8ca)

I noticed this issue already in release r9378

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
This also happens with PreMigration dialog or any other parts which uses AndroidView in the app.

**Comment by cuong-tran** [comment]
fixed in r9484
