### ISSUE TITLE
Label/badge on read titles when removed from library

### ISSUE THREAD

**Issue by Himx18** [komikku-app/komikku#427]
### Describe your suggested feature

Example i've completed naruto and i remove it from my library. The Naruto manga should show a label of a sort that i completed the manga (from the extension i read). 

If im surfing the same extension ABC and i come across Naruto or anyother manga i've completed from the ABC extension, it should show a badge or label on the entry cover of the manga 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
duplicate with #293
