### ISSUE TITLE
Make "hide Entries already in library" also affect the feed

### ISSUE THREAD

**Issue by aoba-seragakii** [komikku-app/komikku#438]
### Describe your suggested feature

Hide the entries that were already added in the feed if this option is active

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
this is done
