### ISSUE TITLE
Add a way to download chapters through reader chapter list

### ISSUE THREAD

**Issue by aoba-seragakii** [komikku-app/komikku#459]
### Describe your suggested feature

To download new chapters while reading, we need to go back to the entry itself. We should be able to download it from the reader's chapter list.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
Marking this as won't fix since there is already one created on SY and the guy who made this - NGB - is overthere, he should do it. But not close this for now in case he won't do it then.

**Comment by cuong-tran** [comment]
Merged
