### ISSUE TITLE
Saved search on feed changed out of nowhere

### ISSUE THREAD

**Issue by kana-shii** [komikku-app/komikku#463]
### Steps to reproduce

1. Have an saved search from a source which usually adds more filters 
2. Wait for it to add another one and see your filters change completely

### Expected behavior

The saved search should always stay the same, even if the filters update

### Actual behavior

If the filters update, the saved filter won't be the same.

### Komikku version

r9484

### Android version

Android 13

### Device

Samsung s20 fe 

### Other details

I'm guessing that the saved search works by the position of the filter in the list, not by the filter name itself 
I think it should work by it's name if possible

1st filter used to have blue lock doujinshis, turned into Blend S doujinshis (which is right after the Blue Lock filter btw)

2nd one used to be Katekyo Hitman Reborn doujinshis, turned into KAT-TUN doujinshis (haven't checked that one but probably right before the Katekyo Hitman Reborn ones)
![Screenshot_20241026_234432_Komikku](https://github.com/user-attachments/assets/9ac5c1d0-305f-4bd1-abda-19bf1df83ba8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by mrtear** [comment]
same happened with me.

![Komikku.jpg](https://github.com/user-attachments/assets/bf92cd0e-4c5e-416b-a6f2-e96893dc3f74)

I've to change the saved search filters again & again after some time.


because of this, It doesn't show the saved search filter properly(shows random content after some time) added in feed.

**Comment by cuong-tran** [comment]
Could you provide a video recording of it changing. Also provide me the app version.
Thanks

**Comment by mrtear** [comment]
> Could you provide a video recording of it changing. Also provide me the app version.
> Thanks

here's everything I can get!

![feed.jpg](https://github.com/user-attachments/assets/cf44e086-96bb-494f-a563-f1a989cf0a3c)

_Part-1_
https://github.com/user-attachments/assets/f4b81ab7-ecb3-477b-92ba-95aaa0d05b88

_Part-2_
https://github.com/user-attachments/assets/8ecbf1d2-9817-483e-86f0-998833e64b01

**Comment by JoeloJoestar** [comment]
@mrtear this happens when the source is updated and the filters may change because of that

**Comment by JoeloJoestar** [comment]
> same happened with me.
> 
> ![Komikku.jpg](https://private-user-images.githubusercontent.com/91820779/383461816-bf92cd0e-4c5e-416b-a6f2-e96893dc3f74.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjUxMjUsIm5iZiI6MTczMDk2NDgyNSwicGF0aCI6Ii85MTgyMDc3OS8zODM0NjE4MTYtYmY5MmNkMGUtNGM1ZS00MTZiLWE2ZjItZTk2ODkzZGMzZjc0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA3MzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlODJkODY5Zjc4NzdkN2ZkYjI1Y2NmNzE0MzA5ZGUyZjZlMmIwZGUwZWMwOGRmOTlkMmYxMzA1ODUxYTg3MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZK2kihRE4oc0M0cpms7V97B8Ju4A8ig3fTMXo2Btfxg)
> 
> I've to change the saved search filters again & again after some time.
> 
> because of this, It doesn't show the saved search filter properly(shows random content after some time) added in feed.

this happens when the source is updated and the filters may change because of that

**Comment by JoeloJoestar** [comment]
Actually I am having the same issue today with Imhentai. I created twice today new filters and after not doing anything in particular nor updating the sources, they got invalid.

Can you please verify this by browsing inside the sources and tapping on the saved filters?
![Screenshot_20241107-133926_Komikku](https://github.com/user-attachments/assets/e66f9391-a3ee-41f6-bda7-d09ac418d696)

Can you also please list the problematic sources?

**Comment by JoeloJoestar** [comment]
About Imhentai saved searches, I've tried with TachiyomiSY latest preview (574) and old stable Komikku build (1.11.1) and they all got the same issue.
[log r9523](https://github.com/user-attachments/files/17674879/2024-11-08-preview.log)

**Comment by cuong-tran** [comment]
Solved with r9576, not completely perfect but should be OK.
