### ISSUE TITLE
Add errors from update screen to backup

### ISSUE THREAD

**Issue by aoba-seragakii** [komikku-app/komikku#464]
### Describe your suggested feature

If they are not included in the backup, will have to update the whole library to find the entries with errors.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
Nah, there is no guarantee an entry is OK today will also OK tomorrow. It might get error anytime. So unless you do whole library update regularly you can't be sure your library is error free.
That means, backup error or not, you still need to do library update anyway.
Sorry.
