### ISSUE TITLE
Bulk change predicted date

### ISSUE THREAD

**Issue by aoba-seragakii** [komikku-app/komikku#471]
### Describe your suggested feature

Add a way to bulk change the predicted dates though the library (by selecting multiple entries that you want to customize the predicted dates)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
Why do you need to do that?

**Comment by aoba-seragakii** [comment]
> Why do you need to do that?

Sometimes predicted date makes the updates get a lot longer because of the amount of entries that will be updated in a single day like 2000 in a single day so i wanted to try to space them out... but to be honest, i've been thinking that this isn't really needed right now and i changed my mind about this issue so i think i'll be closing it
