### ISSUE TITLE
Add a drop down button in updates when there are too many updates of a single manga so that all of them are hidden unless u click on drop down button.

### ISSUE THREAD

**Issue by cuong-tran** [komikku-app/komikku#488]

**Comment by Hepticce** [comment]
Adding also a way to remove or clear updates would be great so that it can give more control and help keep things tidy.

**Comment by Hepticce** [comment]
As someone who’s had their updates constantly filled with the same manga, I know how frustrating it can be to sift through repetitive entries. 🥲
