### ISSUE TITLE
In addition to the same background color

### ISSUE THREAD

**Issue by OtakuArab** [komikku-app/komikku#5]
### Describe your suggested feature

There should be a display feature for the manga, the same dominant color in the background of the work. An example of this is the TachJ2k application, where the display interface for the manga or work is the same color as the background.

### Other details

1- The application interface has normal colors
![Screenshot_٢٠٢٤٠٥١٠-٢٠٥٨١٠_Komikku](https://github.com/komikku-app/komikku/assets/161339329/279840dc-e2ff-41b1-8bc1-9fbd8b1d4288)

2- The display interface of the application  
TachJ2k
![Screenshot_٢٠٢٤٠٥١٠-٢٠٥٧٥٣_Ykai](https://github.com/komikku-app/komikku/assets/161339329/816a0595-41d1-42e1-af72-cde462cac642)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
Yes, it's already in TODO list.

**Comment by cuong-tran** [comment]
working on this

**Comment by OtakuArab** [comment]
> working on this

Excitedly waiting for this feature. Thank you

**Comment by cuong-tran** [comment]
colored is done. Still need fixing some bugs.
