### ISSUE TITLE
Easily download read chapters

### ISSUE THREAD

**Issue by JoeloJoestar** [komikku-app/komikku#506]
### Describe your suggested feature

Chance to download read chapters in the same way is possible for the unread ones, from library and in the entry, then not being forced to manually select them

### Other details
Each of the following options only do concern unread entries:
#### Library
![Screenshot_20241106-133109_Komikku](https://github.com/user-attachments/assets/58653664-f990-4443-b80d-6c32ee473d3f)

#### Entry
![Screenshot_20241106-133131_Komikku](https://github.com/user-attachments/assets/d55c2414-c4ed-4d26-91bb-5a4bad7ff99e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.12.1](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
I believe this is a way upstream discourage users from abusing sources. At least we can still range-select or select All then hit Download.

**Comment by JoeloJoestar** [comment]
> I believe this is a way upstream discourage users from abusing sources. At least we can still range-select or select All then hit Download.

If that was the intention then it failed because from the library we can select infinite entries, tap __Unread__ and enjoy the mass downloading of so many chapters.
With this issue, I am pointing out this discrimination against read chapters in favor of unread ones. 😄
