### ISSUE TITLE
[Feature Request] Make selected manga fully offline.

### ISSUE THREAD

**Issue by HaomingChen1998** [komikku-app/komikku#515]
### Describe your suggested feature

There are some manga that I downloaded locally, and when I view them, the meta data refreshes either automatically or by mistake. In the case where the manga title changes, I'll need to re-download this manga. I assume it's because of manga title change, so that the app can no longer find the downloaded manga. 

Is it possible to cut off internet access completely for selected manga that I know they won't receive update, and are already downloaded? Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.12.1](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
Not really about cut-off internet for specific manga.
But if title changes, the directory should be automatically changed too, by app. If you don't see the downloaded chapters, try go to Settings/Reindex download.

**Comment by cuong-tran** [comment]
Also, I think app won't change title/folder if entry is favorited (in library). If you happens to download chapters without adding it to library, the issue could happens.
