### ISSUE TITLE
Differentiate volume/season/chapter on manga

### ISSUE THREAD

**Issue by xdeiimoss** [komikku-app/komikku#553]
### Describe your suggested feature

Some entries have things in the chapter title like for example:

**Season 1** or **Season 2**
![Screenshot_20241124_145835_Komikku](https://github.com/user-attachments/assets/8e35f71a-a26f-4a9c-90c9-529c1872d027)

**Volume 1** or **Volume 2**
![Screenshot_20241124_150250_Komikku](https://github.com/user-attachments/assets/e9d5e3d3-a37a-48f0-b1de-2d2b0f9e3d1f)

**Side Story 1** or **Side Story 2**
![Screenshot_20241124_150636_Komikku](https://github.com/user-attachments/assets/60429519-8b0c-42ce-acb9-183e8dd0f87d)

And having mark duplicate active actually will mark those as well.

Is it possible to have it know when it should be marked or when it shouldn't?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.12.1](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
That won't work.
