### ISSUE TITLE
Komikku can't load random thumbnail images, but Mihon can.

### ISSUE THREAD

**Issue by FiorenMas** [komikku-app/komikku#563]
### Steps to reproduce

1. Go to both app source TopTruyen (Vi).
2. Scrolling in latest manga and some thumbnails won't load, but Mihon loads normally.

### Expected behavior

Image explain:
Komikku can't load image
![image](https://github.com/user-attachments/assets/ced1bdb8-d60d-40c2-8e83-609bcdb61b3b)

### Actual behavior

Mihon load image normal
![image](https://github.com/user-attachments/assets/09a6e7f4-762e-4a6f-b817-2682668fc58f)

### Komikku version

1.12.1

### Android version

Android 11

### Device

Poco x3 pro

### Other details

I tried use Komikku preview version but still have same problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.12.1](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
TopTruyen doesn't play nice with latest user-agent in Komikku. Set it to default one from Mihon for it to work.
For example: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0`

Remember to Advance/Clear database to clear Toptruyen entries and restart app after changing user-agent.
