### ISSUE TITLE
Support aniyomi/kuukiyomi backups

### ISSUE THREAD

**Issue by 93Pd9s8Jt** [komikku-app/komikku#578]
### Describe your suggested feature

Currently trying to import a kuukiyomi or aniyomi backup gives the error:
![image](https://github.com/user-attachments/assets/38c3e01d-56b2-488e-90b5-b6c676239535)
Ideally kuukiyomi would support these backups.

### Other details

The relevant code in aniyomi, afaict, is at https://github.com/aniyomiorg/aniyomi/tree/master/app/src/main/java/eu/kanade/tachiyomi/data/backup. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.12.1](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
damn bot, you dare to oppose me
