### ISSUE TITLE
Google Drive Sync not working

### ISSUE THREAD

**Issue by SatoX69** [komikku-app/komikku#584]
### Steps to reproduce

Fix sync issues

### Expected behavior

Should properly sync so whenever I open drive, I can see the file or wtv it syncs

### Actual behavior

It says it linked/connected with my drive acc, I also allowed it on the drive linking prompt, I still don't see anything after syncing

### Komikku version

1.12.1

### Android version

Android 14

### Device

OnePlus Nord ce4 lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.12.1](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
What you are talking about is not how GDrive sync work. App can't access your normal GDrive file/folder, it also does not write to there so you won't be able to see anything.
Instead, app is writing to GDrive's App data special location. You can only see its storage usage by going to GDrive's setting/App management.

**Comment by SatoX69** [comment]
Found it, thanks. I honestly didn't know
