### ISSUE TITLE
Two way sync

### ISSUE THREAD

**Issue by HikaruIchijyo** [komikku-app/komikku#62]
### Describe your suggested feature

Is it possible to add two way sync from anilist or other.
Currently it only supports one way sync which is reading to the tracker. What about the other way.
This will be more effective and good  ig?

### Other details

Two way sync is already available in tachs97 which is j2k fork

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
I think 2-way sync should be working already? Have you tried the Beta version?
https://github.com/komikku-app/komikku-preview/releases/latest

**Comment by HikaruIchijyo** [comment]
> I think 2-way sync should be working already? Have you tried the Beta version?
> https://github.com/komikku-app/komikku-preview/releases/latest

Oh no
I am on latest stable

**Comment by cuong-tran** [comment]
I will merge it to stable version soon
