### ISSUE TITLE
Add blur background

### ISSUE THREAD

**Issue by Sukshm** [komikku-app/komikku#69]
### Describe your suggested feature

Add blur background on viewing thumbnail of an entry 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
Like how? Is there any reference from other forks?

**Comment by Sukshm** [comment]
* Open any j2k  manga entry
* Click on thumbnail
* The side of af the thumbnail is what it need

**Comment by cuong-tran** [comment]
> Look intresting https://chrisbanes.github.io/haze/

It's only support Android 12+. And I don't know why but I tested and it won't work on Android 12.
