### ISSUE TITLE
add a way to merge two entries that are already in the library by selecting them

### ISSUE THREAD

**Issue by kana-shii** [komikku-app/komikku#98]
### Describe your suggested feature

1. Basically, by selecting two or more entries, option to merge the entries appear

2. also, if possible make it so merged manga actually turns into one single entry instead of having two (one merged and one original).
basically what I want is to have both original entries disappear
I would technically have both original entries in my library only through the merged entry, but not individually 
And then, if I wish to have the original individual entries back I would unmerge them (through a button or something like that)

(it would be a bonus if when clicking in the entry through the history tab, it would only show the merged entry instead of two separate original entries)

![image](https://github.com/komikku-app/komikku/assets/79055104/0f1b3d55-39cf-4fd9-8bb4-d31bd2082f6f)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
this is done
